- name: install and run nginx 
  host: web
  become: yes # equal to -b in adhoc commands, getting root access
  task:
  - name: install nginx 
    ansible.builtin.dnf:
      name: nginx
      state: latest
  - name: start nginx
    ansible.builtin.service:
      name: nginx
      state: start
      enabled: yes    
