
- name: variables from files
  hosts: localhost
  tasks: 
  - name: print information
    ansible.builtin.debug:
      msg: "Hello I am new to {{Course}} but it's deploying wise very powerfull,Duration is {{Duration}}"