- name: conditions
  hosts: web
  become: yes
  tasks:
  - name: check user exists or not
    ansible.builtin.command: id expense
    register: USER
    ignore_errors: true
    
  - name: Print user infrmation
    ansible.builtin.debug: 
      msg: "User info: {{USER}}"  

  - name: say Hello
    ansible.builtin.debug:
      msg: "Hello"   