- name: check number
  hosts: web
  vars_prompt:
  - name: number
    prompt: please enter number
    private: no
  tasks:
  - name: number is lessthan 10
    ansible.builtin.debug:
      msg: "Given number {{number}} is less than 10"
    when: number < 10

  - name: number is lessthan 10
    ansible.builtin.debug:
      msg: "Given number {{number}} is less than 10"
    when: number >= 10

