- name: install packages
  hosts: web
  become: yes       
  tasks: 
  - name: install packages
    ansible.builtin.dnf:
      name: "{{ item.name }}"
      state: "{{ item.state}}"
      name: "{{ item }}"
      state: latest
    loop:
    - {name: nginx state: 'absent'}

     